  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
    sql:
      init:
        mode: always

    security:
      oauth2:
        resourceserver:
          jwt:
            expiration: 1800000
            secretKey: L6PjdqNHoHk8kTiB8uFzPMy4rFQzyJoD35qFhT3EfMk=
    application:
      mailing:
        frontend:
          activation-url: "http://localhost:4200/code-verify"

    mail:
      host: localhost
      port: 1025
      username: username
      password: password
      properties:
        mail:
          smtp:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


